// lib/core/models/staff.dart
import 'dart:convert';
import 'dart:math';
import 'package:crypto/crypto.dart';

enum StaffRole { owner, manager, cashier, kitchen }

extension StaffRolePermissions on StaffRole {
  String get key => switch (this) {
        StaffRole.owner => 'owner',
        StaffRole.manager => 'manager',
        StaffRole.cashier => 'cashier',
        StaffRole.kitchen => 'kitchen',
      };
}

extension StaffRoleX on StaffRole {
  String get label => switch (this) {
        StaffRole.owner => 'Owner',
        StaffRole.manager => 'Manager',
        StaffRole.cashier => 'Cashier',
        StaffRole.kitchen => 'Kitchen',
      };

  String get value => name;

  bool get canAccessPOS =>
      this == StaffRole.owner ||
      this == StaffRole.manager ||
      this == StaffRole.cashier;

  bool get canAccessOrders =>
      this == StaffRole.owner ||
      this == StaffRole.manager ||
      this == StaffRole.cashier;

  bool get canAccessKitchen =>
      this == StaffRole.owner ||
      this == StaffRole.manager ||
      this == StaffRole.kitchen;

  bool get canAccessInventory =>
      this == StaffRole.owner || this == StaffRole.manager;

  bool get canAccessReports => this == StaffRole.owner;

  bool get canAccessSettings => this == StaffRole.owner;
}

/// Returns the assignable (non-owner) roles available for a given business type.
/// Retail: cashier only.
/// Restaurant: manager, cashier, kitchen.
extension StaffRoleAvailability on StaffRole {
  static List<StaffRole> forBusinessType(bool isRestaurant) {
    if (isRestaurant) {
      return [StaffRole.manager, StaffRole.cashier, StaffRole.kitchen];
    }
    return [StaffRole.cashier];
  }
}

class StaffMember {
  final String id;
  final String businessId;
  final String name;
  final StaffRole role;
  final String pinHash;
  final String? pinSalt;
  final bool isActive;

  const StaffMember({
    required this.id,
    required this.businessId,
    required this.name,
    required this.role,
    required this.pinHash,
    this.pinSalt,
    required this.isActive,
  });

  factory StaffMember.fromJson(Map<String, dynamic> json) => StaffMember(
        id: json['id'] as String,
        businessId: json['business_id'] as String,
        name: json['name'] as String,
        role: StaffRole.values.firstWhere(
          (r) => r.value == json['role'],
          orElse: () => StaffRole.cashier,
        ),
        pinHash: json['pin_hash'] as String,
        pinSalt: json['pin_salt'] as String?,
        isActive: json['is_active'] as bool? ?? true,
      );

  Map<String, dynamic> toJson() => {
        'business_id': businessId,
        'name': name,
        'role': role.value,
        'pin_hash': pinHash,
        'pin_salt': pinSalt,
        'is_active': isActive,
      };

  /// Generates a cryptographically random 32-byte hex salt.
  static String generateSalt() {
    final rng = Random.secure();
    final bytes = List<int>.generate(32, (_) => rng.nextInt(256));
    return bytes.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }

  /// Hashes a PIN with a salt using PBKDF2-SHA256 (10,000 iterations).
  /// Salt must be a hex string generated by [generateSalt].
  static String hashPin(String pin, String salt) {
    // PBKDF2 via repeated HMAC-SHA256
    final saltBytes = _hexToBytes(salt);
    final pinBytes = utf8.encode(pin.trim());
    var block = List<int>.from(pinBytes + saltBytes);
    for (var i = 0; i < 10000; i++) {
      block = Hmac(sha256, pinBytes).convert(block).bytes;
    }
    return block.map((b) => b.toRadixString(16).padLeft(2, '0')).join();
  }

  /// Legacy hash — SHA-256 with no salt.
  /// Only used to detect and upgrade old PINs on login.
  static String _legacyHash(String pin) {
    final bytes = utf8.encode(pin);
    return sha256.convert(bytes).toString();
  }

  static List<int> _hexToBytes(String hex) {
    final result = <int>[];
    for (var i = 0; i < hex.length; i += 2) {
      result.add(int.parse(hex.substring(i, i + 2), radix: 16));
    }
    return result;
  }

  /// Returns true if [pin] matches, false otherwise.
  /// If the stored hash is legacy (no salt), falls back to legacy check.
  bool checkPin(String pin) {
    if (pinSalt != null) {
      // New salted PBKDF2 hash
      return hashPin(pin, pinSalt!) == pinHash;
    }
    // Legacy: unsalted SHA-256 — still works but triggers upgrade on login
    return _legacyHash(pin) == pinHash;
  }

  /// Returns true if this staff member still uses the old unsalted hash.
  bool get needsPinUpgrade => pinSalt == null;
} 